#!/usr/bin/env bash
# bootstrap.sh — generate .harness/ scaffold from LLM-provided detection JSON
# Stack/commands/ui detection is done by the LLM (see modes/bootstrap.md),
# then passed in via --config. This script is pure scaffold generation.
# Usage:
#   bootstrap.sh --config '<json>'           # plan only, no writes
#   bootstrap.sh --apply --config '<json>'   # write all files
#
# Required JSON shape (minimal):
#   { "root": "/abs/path",
#     "stack": "node|python|rust|...",
#     "package_manager": "npm|pnpm|...",
#     "commands": {"install":..., "test":..., "lint":..., "build":..., "dev":...},
#     "ui": {"framework": "...", ...} | null }
set -euo pipefail

APPLY=0
CONFIG_OVERRIDE=""
HOOKS=1               # default: install hooks (framework-mode)
HOOK_LEVEL="standard" # minimal | standard | aggressive

while [ $# -gt 0 ]; do
  case "$1" in
    --apply) APPLY=1; shift ;;
    --config) CONFIG_OVERRIDE="$2"; shift 2 ;;
    --no-hooks) HOOKS=0; shift ;;
    --hook-level) HOOK_LEVEL="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [ -z "$CONFIG_OVERRIDE" ]; then
  echo '{"error":"--config <json> required (LLM must detect stack first, see modes/bootstrap.md)"}' >&2
  exit 2
fi
DETECTED="$CONFIG_OVERRIDE"

python3 - "$APPLY" "$DETECTED" <<'PYEOF'
import json, os, sys
from datetime import datetime

apply = sys.argv[1] == "1"
detected = json.loads(sys.argv[2])
root = detected["root"]

would_create = []
would_modify = []
existing = []

paths = {
    "config": ".harness/config.json",
    "progress": ".harness/progress.md",
    "features": ".harness/feature_list.json",
    "lessons": ".harness/lessons.md",
    "init": ".harness/init.sh",
}

for k, p in paths.items():
    full = os.path.join(root, p)
    (existing if os.path.exists(full) else would_create).append(p)

claude_md = os.path.join(root, "CLAUDE.md")
if os.path.exists(claude_md):
    with open(claude_md) as f:
        if "harness skill" in f.read().lower():
            pass
        else:
            would_modify.append("CLAUDE.md")
else:
    would_create.append("CLAUDE.md")

# Build config
cmds = detected.get("commands", {})
config = {
    "stack": detected.get("stack", "unknown"),
    "package_manager": detected.get("package_manager"),
    "commands": cmds,
    "ui": detected.get("ui"),
    "_generated_by": "harness-bootstrap",
    "_generated_at": datetime.utcnow().isoformat() + "Z",
}

# Templates
TEMPLATES = {
    "config": json.dumps(config, ensure_ascii=False, indent=2),
    "init": f"""#!/usr/bin/env bash
# .harness/init.sh — standard project init (regenerated by /harness-bootstrap)
set -euo pipefail
cd "$(dirname "${{BASH_SOURCE[0]}}")/.."
echo "[1/3] {cmds.get('install', 'install...')}"
{cmds.get('install', 'echo no install command')}
echo "[2/3] {cmds.get('check', cmds.get('test', 'verify...'))}"
{cmds.get('check', cmds.get('test', 'echo no verify command'))}
echo "[3/3] ready. dev: {cmds.get('dev', 'see README')}"
""",
    "progress": """# Progress

## 當前已驗證狀態

- 倉庫根目錄: """ + root + """
- 標準啟動: `""" + cmds.get("dev", "?") + """`
- 標準驗證: `""" + cmds.get("test", "?") + """`
- 當前最高優先級未完成: (待 user 填)
- 當前 blocker: 無

## 會話記錄

（每輪由 `/harness-handoff` 追加，使用 YAML frontmatter）
""",
    "features": json.dumps({
        "project": detected.get("_pkg_name", os.path.basename(root)),
        "rules": {
            "single_active_feature": True,
            "passing_requires_evidence": True,
            "evidence_must_be_command": True
        },
        "_schema_example": {
            "id": "feature-id",
            "status": "passing|in-progress|missing",
            "evidence": {
                "command": "<shell command to verify>",
                "expected_exit": 0,
                "safe": True,
                "verified_at": "ISO timestamp (only meaningful when safe=false)"
            }
        },
        "_safe_field_note": "safe=true (default): re-runnable any time (npm test, type-check). safe=false: needs env / mutates state / long-running (db migrate, dev server, e2e). verify-features.sh skips unsafe by default; use --full to include them.",
        "features": []
    }, ensure_ascii=False, indent=2),
    "lessons": """# Lessons（永久防線清單）

由 `/harness-promote-lesson` 維護。每條規則包含：
- 規則描述
- 強制方式（lint / test / pre-commit / docs）
- 強制位置（檔案 + 行號）
- 來源（哪個錯誤啟發的）
- 歷史違規數
""",
}

CLAUDE_MD_SECTION = """
## Harness

此 project 已啟用 harness skill (`~/.claude/skills/harness/`)。

**會話開始時：**
1. `cat .harness/progress.md` 看當前狀態
2. `cat .harness/feature_list.json` 看功能狀態
3. `bash .harness/init.sh` 確認 baseline 乾淨

**會話結束時：**
1. `/harness-handoff` 更新 progress（也會由 Stop hook 自動跑）
2. 確認所有測試通過

**所有命令在** `.harness/config.json`。
"""

plan = {
    "detected": detected,
    "would_create": would_create,
    "would_modify": would_modify,
    "existing_will_skip": existing,
    "applied": False,
}

if apply:
    os.makedirs(os.path.join(root, ".harness"), exist_ok=True)
    written = []
    for k, p in paths.items():
        full = os.path.join(root, p)
        if os.path.exists(full) and k != "config":
            continue  # don't overwrite progress/features/lessons/init
        with open(full, "w") as f:
            f.write(TEMPLATES[k])
        if k == "init":
            os.chmod(full, 0o755)
        written.append(p)
    # CLAUDE.md
    if "CLAUDE.md" in would_modify or not os.path.exists(claude_md):
        with open(claude_md, "a") as f:
            f.write(CLAUDE_MD_SECTION)
        written.append("CLAUDE.md (appended)")
    plan["applied"] = True
    plan["written"] = written

print(json.dumps(plan, ensure_ascii=False, indent=2))
PYEOF

# Install hooks (framework-mode) after scaffold is in place
if [ "$APPLY" = "1" ] && [ "$HOOKS" = "1" ]; then
  LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  echo "---hooks---"
  "$LIB_DIR/install-hooks.sh" --level "$HOOK_LEVEL" || echo '{"warning":"hook install failed; harness still works via slash commands"}'
fi
